ACTION_SPACE_SIZE = 4
MAX_EXPERIENCE_BUFEER_SIZE = 500000
MIN_EXPERIENCE_BUFFER_SIZE = MAX_EXPERIENCE_BUFEER_SIZE // 10
TARGET_UPDATE_PERIOD_CAP = 100000
TARGET_UPDATE_PERIOD_NEW = 10000
TARGET_UPDATE_PERIOD_OLD = TARGET_UPDATE_PERIOD_NEW // 2
IM_SIZE = 84